### ISSUE TITLE
conditional require leads to load error

### ISSUE THREAD

**Issue by Vimos** [classdojo/amdify.js#13]
amdify::getRequired may need to consider the following conditional require
module.exports = process.env.EXPRESS_COV
? require('./lib-cov/express')
: require('./lib/express');

which sometimes may load problems

cannot load "./lib-cov/express" in "/home/vimos/Public/git/oct_suggestion/build/matchn/node_modules/express"
unable to include script /home/vimos/Public/git/oct_suggestion/build/matchn/node_modules/express/index.js from /home/vimos/Public/git/oct_suggestion/build/matchn/app.js, Error: Cannot find module './lib-cov/express'
    at Function.module.exports [as sync]

**Comment by rlidwka** [comment]
I think it should be reported to express, there is no way amdify could parse those.
